import React, { useEffect, useMemo, useState } from "react";
import { createPortal } from "react-dom";
import { api } from "../api";
import {
  readProgress,
  sheetFilename,
  toggleStep,
  quantityLabel,
} from "../utils/worksheet.js";

/**
 * The splice worksheet: the box's documentation as a checklist a technician works
 * through, with a print button and a plain-text copy for a phone.
 *
 * Everything on it is generated by the API from the box's own documentation
 * (`GET /api/work-orders/:boxId`), so the sheet cannot disagree with the panel it
 * came from. Ticks are kept in this browser, per work order.
 */
export default function WorkOrderSheet({ boxId, boxCode, onClose }) {
  const [order, setOrder] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const [by, setBy] = useState("");
  const [kind, setKind] = useState("splice");
  const [done, setDone] = useState([]); // step numbers ticked on this device
  const [copied, setCopied] = useState(false);

  useEffect(() => {
    let cancelled = false;
    setLoading(true);
    api
      .getWorkOrder(boxId, { by: by || undefined, kind })
      .then((data) => {
        if (cancelled) return;
        setOrder(data);
        setError(null);
      })
      .catch((e) => !cancelled && setError(e.message))
      .finally(() => !cancelled && setLoading(false));
    return () => {
      cancelled = true;
    };
  }, [boxId, by, kind]);

  // Ticks belong to the work order, so a sheet regenerated tomorrow starts clean.
  useEffect(() => {
    if (order) setDone(readProgress(order.work_order.reference));
  }, [order]);

  const steps = useMemo(
    () => (order?.checklist || []).filter((item) => !item.info && item.step),
    [order],
  );
  const progress = useMemo(() => {
    const ticked = steps.filter((item) => done.includes(item.step)).length;
    return {
      done: ticked,
      total: steps.length,
      label: `${ticked}/${steps.length}`,
      complete: steps.length > 0 && ticked === steps.length,
    };
  }, [steps, done]);

  const tick = (step) => {
    if (!order) return;
    setDone(toggleStep(order.work_order.reference, step));
  };

  const copyText = async () => {
    try {
      const text = await api.getWorkOrderText(boxId, { by: by || undefined, kind });
      await navigator.clipboard.writeText(text);
      setCopied(true);
      setTimeout(() => setCopied(false), 1500);
    } catch (e) {
      setError(e.message);
    }
  };

  const downloadText = async () => {
    try {
      const text = await api.getWorkOrderText(boxId, { by: by || undefined, kind });
      const blob = new Blob([text], { type: "text/plain;charset=utf-8" });
      const url = URL.createObjectURL(blob);
      const anchor = document.createElement("a");
      anchor.href = url;
      anchor.download = sheetFilename(order);
      anchor.click();
      URL.revokeObjectURL(url);
    } catch (e) {
      setError(e.message);
    }
  };

  // Into <body>: the print rules hide the panel this button lives in, and the
  // checklist is exactly what should come out of the printer.
  return createPortal(
    <div className="sheet-overlay" role="dialog" aria-label="Splice worksheet">
      <div className="sheet-panel sheet-panel-wide">
        <div className="sheet-toolbar no-print">
          <span className="sheet-title">Splice worksheet — {boxCode || boxId}</span>
          <label className="sheet-field">
            Job
            <select value={kind} onChange={(e) => setKind(e.target.value)}>
              <option value="splice">Splice job</option>
              <option value="repair">Repair job</option>
              <option value="survey">Documentation survey</option>
            </select>
          </label>
          <label className="sheet-field">
            Technician
            <input
              value={by}
              placeholder="your name"
              onChange={(e) => setBy(e.target.value)}
              style={{ width: 130 }}
            />
          </label>
          <button className="btn" onClick={() => window.print()} disabled={!order}>
            Print
          </button>
          <button className="btn" onClick={copyText} disabled={!order}>
            {copied ? "Copied" : "Copy text"}
          </button>
          <button className="btn" onClick={downloadText} disabled={!order}>
            Download .txt
          </button>
          <button className="btn" onClick={onClose}>
            Close
          </button>
        </div>

        {loading && <p className="loading-row">Building the worksheet from this box's documentation…</p>}
        {error && <p className="error-row">{error}</p>}

        {order && (
          <div className="worksheet print-area">
            <header className="worksheet-head">
              <div>
                <h2>{order.work_order.title}</h2>
                <p className="worksheet-meta">
                  {order.work_order.reference}
                  {order.work_order.generated_by ? ` · for ${order.work_order.generated_by}` : ""}
                  {" · generated "}
                  {new Date(order.work_order.generated_at).toLocaleString()}
                </p>
              </div>
              <div className="worksheet-progress">
                <strong>{progress.label}</strong>
                <span>steps done</span>
              </div>
            </header>

            <p className="worksheet-summary">
              {order.summary.cables} cables · {order.summary.cores} fibres ·{" "}
              {order.summary.splices} splices on record · {order.summary.splitters} splitters
              {order.summary.free_splitter_ports
                ? ` · ${order.summary.free_splitter_ports} free port${order.summary.free_splitter_ports === 1 ? "" : "s"}`
                : ""}
              {order.summary.damaged_cores ? ` · ${order.summary.damaged_cores} damaged` : ""}
              {order.summary.bad_splices ? ` · ${order.summary.bad_splices} over the loss limit` : ""}
            </p>

            <h3>Checklist</h3>
            <ol className="worksheet-steps">
              {order.checklist.map((item) =>
                item.info ? (
                  <li key={`info-${item.task}`} className="worksheet-info">
                    <span className="worksheet-info-mark">i</span>
                    <div>
                      <strong>{item.task}</strong>
                      {item.detail && <p>{item.detail}</p>}
                    </div>
                  </li>
                ) : (
                  <li key={`step-${item.step}`} className={done.includes(item.step) ? "worksheet-done" : ""}>
                    <label className="worksheet-step">
                      <input
                        type="checkbox"
                        checked={done.includes(item.step)}
                        onChange={() => tick(item.step)}
                      />
                      <span className="worksheet-step-body">
                        <span className="worksheet-step-task">
                          <span className="worksheet-step-number">{item.step}.</span> {item.task}
                        </span>
                        {item.detail && <span className="worksheet-step-detail">{item.detail}</span>}
                      </span>
                    </label>
                  </li>
                ),
              )}
            </ol>

            <h3>Materials</h3>
            <table className="worksheet-table">
              <thead>
                <tr>
                  <th>Qty</th>
                  <th>Item</th>
                  <th>Why</th>
                </tr>
              </thead>
              <tbody>
                {order.materials.map((material) => (
                  <tr key={material.item}>
                    <td>{quantityLabel(material)}</td>
                    <td>{material.item}</td>
                    <td>{material.detail || ""}</td>
                  </tr>
                ))}
              </tbody>
            </table>

            {order.splices.length > 0 && (
              <>
                <h3>Splices on record</h3>
                <table className="worksheet-table">
                  <thead>
                    <tr>
                      <th>Side A</th>
                      <th>Side B</th>
                      <th>Loss</th>
                      <th>Tray</th>
                      <th>Date</th>
                    </tr>
                  </thead>
                  <tbody>
                    {order.splices.map((splice) => (
                      <tr key={splice.id} className={splice.loss_db != null && Number(splice.loss_db) > order.qc_flags.bad_splice_threshold_db ? "worksheet-bad" : ""}>
                        <td>{splice.cable_a_code} #{splice.core_a_number}</td>
                        <td>{splice.cable_b_code} #{splice.core_b_number}</td>
                        <td>{splice.loss_db == null ? "—" : `${Number(splice.loss_db).toFixed(2)} dB`}</td>
                        <td>{[splice.tray_number, splice.tray_position].filter(Boolean).join("/") || "—"}</td>
                        <td>{splice.splice_date ? String(splice.splice_date).slice(0, 10) : "—"}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </>
            )}

            {order.cables_landing_here.length > 0 && (
              <>
                <h3>Fibres in this box</h3>
                <table className="worksheet-table worksheet-fibres">
                  <thead>
                    <tr>
                      <th>Dir</th>
                      <th>Cable</th>
                      <th>#</th>
                      <th>Status</th>
                      <th>Far end</th>
                    </tr>
                  </thead>
                  <tbody>
                    {order.cables_landing_here.flatMap((group) =>
                      group.cores.map((core) => (
                        <tr key={core.id}>
                          <td>{group.direction === "in" ? "IN" : group.direction === "out" ? "OUT" : "·"}</td>
                          <td>{group.cable.code}</td>
                          <td>{core.core_number}</td>
                          <td>{core.status}</td>
                          <td>
                            {core.far_endpoint && core.far_endpoint.connection !== "free"
                              ? `${core.far_endpoint.label}${core.far_endpoint.enclosure_code ? ` at ${core.far_endpoint.enclosure_code}` : ""}`
                              : "—"}
                          </td>
                        </tr>
                      )),
                    )}
                  </tbody>
                </table>
              </>
            )}

            <div className="worksheet-signoff">
              <p>Technician: ____________________ Date: ____________</p>
              <p>Loss readings recorded in the app: ☐ yes &nbsp;&nbsp; Box closed and locked: ☐ yes</p>
            </div>
          </div>
        )}
      </div>
    </div>,
    document.body,
  );
}
